#rn "mvnw package" before build and run docker img
version: '3.8'
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'iptu'
      MYSQL_ROOT_PASSWORD: '123123'
    volumes:
      - ./mysql_data:/var/lib/mysql
    container_name: db-iptu
    ports:
      - '3306:3306'
    expose:
      - '3306'
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=$$MYSQL_ROOT_PASSWORD --execute \"SHOW DATABASES;\""
      interval: 2s
      timeout: 10s
      retries: 10